### PR TITLE
WIP:Initial refactoring

### PR DESCRIPTION
**Pull request by enesTufekci**

### CODE REVIEW

**Comment by mxfactorial** [comment]
Parity with master TODOs
- [ ] Add [signUp](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#signup)
- [ ] Fix simultaneous inactive debit and credit button bug. Pass a [single reference](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/src/containers/HomeScreen/HomeScreen.js#L96) in state to an active debit or credit button (doesn't matter) to function inverting subsequent state of buttons.
- [ ] Fix contemporaneous update to total transaction value as individual transaction values are added (controlled components)
- [ ] Add [RemoveIcon](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/src/components/TransactionItem/RemoveIcon.js)
- [ ] Allow adding multiple transaction items despite other incomplete items
- [ ] [Auto-scroll](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/src/containers/HomeScreen/HomeScreen.js#L117) when adding transaction item
- [ ] Transaction input values remain editable after they're added
- [ ] Restore e2e test coverage [[1](https://github.com/systemaccounting/mxfactorial-web/pull/8/commits/af6251114ecfb7cd105043dac96d8c4d42119741)] [[2](https://github.com/systemaccounting/mxfactorial-web/pull/8/commits/59dbc468a799da1e654cf6500b9e6d189e2d5869)]
  - [ ] [activeDebitCreditButtons.test.js](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/activeDebitCreditButtons.test.js)
  - [ ] [createAccountE2e.test.js](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/createAccountE2e.test.js) (add [assertion](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/createAccountE2e.test.js#L94) for e2e create account test)
  - [ ] [homeScreenInventory.test.js](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/homeScreenInventory.test.js)
  - [ ] [landingScreen.test.js](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/landingScreen.test.js)
  - [ ] [mobileNavMenu.test.js](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/mobileNavMenu.test.js)
  - [ ] [modifyItemCount.test.js](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/modifyItemCount.test.js)
  - [ ] [noTestButtons.test.js](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/noTestButtons.test.js)
  - [ ] [sumItems.test.js](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/sumItems.test.js)
- [ ] Remove horizontal rule between transaction items

**Comment by enesTufekci** [comment]
Hey @mxfactorial I need additional info about;
> Allow adding multiple transaction items despite other incomplete items
> Remove horizontal rule between transaction items

**Comment by mxfactorial** [comment]
i. **Allow adding multiple transaction items despite other incomplete items**

**Steps**
1. Add value to `name` transaction input.
2. Do not add value to `price` transaction input.
3. Add value to `quantity` input.
4. Select add item button.

**Expected**: Another set of `name`, `price` and `quantity` inputs appear at bottom of transaction item list despite a missing `price` value in initial transaction item set.

new-item

ii. **Remove horizontal rule between transaction items**

**Steps**
1. Select add transaction item button.

**Expected:** Remove transaction item icon serves as visual separator between transactions.

remove-separator

**Observed:** Horizontal rule serves as visual separator between transactions

no-hrule

**Comment by mxfactorial** [comment]
Please restore these cases from master:

1. Keep UX permissive by completely removing "+ item" disable button code, i.e. even if all values are empty, the user may add items (avoids use case friction). Will add pop-up later asking user if they wish to POST after detecting incomplete values (POST endpoint will only pass items where name.length > 0 && price.length > 0 && quantity.length > 0).

2. Allow removal of last item:

Observed:

remove-item-refactor

Expected:

remove-item-master

3. Uniform distance of remove item buttons (e.g. 30px)

Observed:

uniform-distance

4. Bold nav menu lines

Observed:

refactor-nav-button

Expected:

master-nav-button

5. Select sign in button shows home screen instead of landing screen with "account" placeholder

Observed:

sign-in-refactor

Expected:

sign-in-master

6. Show Request and Transact buttons by default. Revealing Trasact vs Request buttons after toggling between credit and debit buttons informs user of their purpose.

Expected:

transact-request-master

**Comment by enesTufekci** [comment]
- [ ] Allow empty transaction items.

- [ ] Allow remove last item.

- [ ]  Uniform distance of remove item buttons 

- [ ]  Bold nav menu lines

- [ ]  Show Request and Transact buttons by default.

**Comment by mxfactorial** [comment]
Uncross your fingers, you'll need them:

1. Please fix and add e2e coverage for unstable cursor:
unstable-cursor

2. Please fix and add e2e coverage for items.length > 0:

items-equal-zero

3. Restore `initial-refactoring` landing screen:

initial-refactoring-landing-screen

to `master` landing screen:
master-landing-screen

4. Eliminate `React.createElement: type is invalid` warning from Form.test.js:

type-warning

5. Add [e2e create account assertion](https://github.com/systemaccounting/mxfactorial-web/blob/7856df1ab93e5c42a5b057dbf620677ccb9458f2/e2e/createAccountE2e.test.js#L94):

assertion-checklist

missing-assertion

6. Also, please eliminate all `<hr>`s from home screen.

7. Please increase horizontal and vertical margin spacing of remove item icon, or return `master` styling:

remove-icon-spacing

**Pull request merged**
