### PR TITLE
Request screen

### PR DESCRIPTION
**Pull request by enesTufekci**

### CODE REVIEW

**Comment by mxfactorial** [comment]
Please:
1. Assign unique identifiers written in [1.1.2 of wireframe](https://docs.google.com/drawings/d/1cF2Ai_lmOaXXI8Z2hso7tbWoNouYNgJ9eFCQES0rPcU/edit?usp=sharing) to elements in `data-id` since `styled-components` is replacing class names. The implementation **must map** the string identifiers in the wireframe so coverage of requirements by automated tests is measurable. Welcome to use kebab-case instead of camelCase (`request-item-indicator` vs. `requestItemIndicator`), but please add css-selectable identifiers for all elements in current set of requirements.

2. Building request feature means only `(debitor_approval_time || creditor_approval_time)`, so account balance on home screen is 0 until transaction feature is finished `(debitor_approval_time && creditor_approval_time)`. 

3. Adjust height and color of `request-item-indicator` to match wireframe.

4. Use minus signs instead of parentheses for negative numbers as required in the [August 18 comment](https://github.com/systemaccounting/mxfactorial-web/issues/3#issuecomment-414097553). The wireframe was updated to eliminate confusion.

5. Print unformatted `debitor_approval_time` or `creditor_approval_time` value in `request-item-indicator` instead of `in 2 months` Formatting and translation of datetime requirements will be added later.

6. Agile request: Add `home-button` to post-auth component to enable navigation from request screen to home screen ([asset](https://drive.google.com/file/d/1Z4hCv_eZMvTXtJQwahbXqFnMTGak7BQi/view?usp=sharing)).

**Comment by mxfactorial** [comment]
Also, please change request to merge into `develop`.

**Comment by mxfactorial** [comment]
1-6 accepted. Please fix and add coverage to these in this branch:
https://github.com/systemaccounting/mxfactorial-web/issues/17 sumTransactionItemIndicator arithmetic failure 
https://github.com/systemaccounting/mxfactorial-web/issues/18 Delete transaction item failure 
Please comment link to automated tests in each issue for tracking.

**Comment by enesTufekci** [comment]
@mxfactorial please check latest updates. Problem was visual when i checked the component with react dev tools I saw `transaction` object passed to child component successfully but `Form` component wasnt getting updated with latest values. I used `getDerivedStateFromProps` lifecycle method to update with latest values and problem solved.

**Comment by mxfactorial** [comment]
> Problem was visual ..

End to end tests cover visual errors, @enesTufekci. The bugs introduced in refactor were not detected because the [test covering this case prior to refactor](https://github.com/systemaccounting/mxfactorial-web/blob/93775c67e8720ec8e7a79354cb6c9613136db9c2/src/e2e/sumItems.test.js#L120-L156) was replaced by [a version more convenient for the developer](https://github.com/systemaccounting/mxfactorial-web/blob/54ddeab307ee5694e2fb3f370b720792f730611f/e2e/transactionAddRemove.test.js#L108-L131), but less convenient for the repo's owner (manual testing, which is time consuming, was required to discover these bugs).

To avoid in the future, and in exchange for receiving detailed requirements, please begin the following process:
1. Label each requirement, feature or bug, with the `automatable` label to identify it as ready for automation. Please begin with https://github.com/systemaccounting/mxfactorial-web/issues/17 _sumTransactionItemIndicator arithmetic failure_ **and** https://github.com/systemaccounting/mxfactorial-web/issues/18 _Delete transaction item failure_.
2. Add estimation to each task.
3. Begin and complete each task after approval.
4. Comment link to issue in automated test.
5. Comment link to automated test line-range in issue.

Continue issuing estimations accounting for adding automated tests, and please **also** treat the requirements received in manual test form as requirements for automated tests. Repo owner doesn't deserve, or has time, to manually test 'completed' code.

**Comment by enesTufekci** [comment]
Totally agreed, sorry for inconvenience. I was going to write new e2e tests to prevent these kind of problems.

**Comment by enesTufekci** [comment]
@mxfactorial I added multiple add/remove transaction item e2e tests. It looks fine to me. If you think its enough we can get this merged.

**Comment by mxfactorial** [comment]
Code and test still broken @enesTufekci https://github.com/systemaccounting/mxfactorial-web/issues/17#issuecomment-421669701

**Comment by mxfactorial** [comment]
Another regression bug @enesTufekci: https://github.com/systemaccounting/mxfactorial-web/issues/20 _Transaction item greater than 0 failure_.

**Pull request merged**
